server:
  port: 9001   #default port where the service will be started
  use-forward-headers: true
 
eureka:         #tells about the Eureka server details and its refresh time
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
 
spring:    
  application:
    name: deinwagen   #current service name to be used by the eureka server
     
management:
  security:
    enabled: false  #disable the spring security on the management endpoints like /env, /refresh etc.
 
logging:
  level:
    com.auma.deinwagen: DEBUG
    
zuul:
  add-host-header: true
  
  sensitive-headers: 
  sensitiveHeaders:  
 
  
   
  
  host:
    connect-timeout-millis: 30000
    socket-timeout-millis: 300000
    




#  routes:
#    auth:
#      path: /auth/**
#      sensitiveHeaders: Cookie,Set-Cookie
#      url: /**

#  routes:
#    auth:
#      sensitiveHeaders:
#      path: /auth/**
#      stripPrefix: false
      
      

#  routes:
#    users:
#      path: /myusers/**
#      sensitiveHeaders:
#      url: https://downstream
  



  routes:
    auth:
      path: /auth/**
      sensitiveHeaders:       
    vehicle:
      path: /vehicle/**
      sensitiveHeaders:
      




  add-proxy-headers: true
  
  
  
  ignore-security-headers: false
  
  
